# 1. Tensors

A Tensor is a multi-dimensional matrix containing elements of a single data type.  
*Everything in PyTorch is based on Tensor operations*

In [1]:
import torch

In [8]:
# torch.empty(size): uninitiallized   
# This creates a tensor without initializing the values. 
# That means the values in the tensor are just whatever was already in that block of memory (often garbage values).
x = torch.empty(1) # scalar
print("empty(1):", x)

x = torch.empty(3) # vector
print("\nempty(3):",x)

x = torch.empty(2, 3) # matrix
print("\nempty(2,3):",x)

x = torch.empty(2, 2, 3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print("\nempty(2, 2, 3):",x)

# torch.rand(size): random numbers [0, 1] but more uniform
x = torch.rand(5, 3)
print("\nrand(5,3):", x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print("\nzeros(5,3):", x)

empty(1): tensor([0.])

empty(3): tensor([2.4435e-04, 9.2486e-43, 2.3694e-38])

empty(2,3): tensor([[0., 0., 0.],
        [0., 0., 0.]])

empty(2, 2, 3): tensor([[[2.4992e-04, 9.2486e-43, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

rand(5,3): tensor([[0.7559, 0.6170, 0.1351],
        [0.8258, 0.7403, 0.9201],
        [0.6040, 0.5004, 0.8114],
        [0.0159, 0.9595, 0.0955],
        [0.4929, 0.5597, 0.7030]])

zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# check size -- both same x.shape is more pythonic, x.size is like legacy code
print("size", x.size())  
print("shape", x.shape)  

size torch.Size([5, 3])
shape torch.Size([5, 3])


In [10]:
# check data type -- usually tensors are float32
print(x.dtype)

# but you can also specify while types while initializing
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [11]:
# cconstruct a tensor by feeding the data
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [14]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


# Operations with Tensor

In [20]:
# Operations
x = torch.ones(2, 2)
y = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y) #both same

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x) # more like y = x + y

print(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8777, 0.8913],
        [0.6091, 0.6113]])
tensor([[1.8777, 1.8913],
        [1.6091, 1.6113]])


In [21]:
# subtraction
z = x - y
z = torch.sub(x, y)   # both same


# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

In [23]:
# Slicing
x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows, column 0
print("x[1, :]", x[1, :]) # row 1, all columns
print("x[1, 1]", x[1,1]) # element at 1, 1

# .item will give the actual float value not just the tensor (va;id only if you havre one element in your tensor)
print("x[1,1].item()", x[1,1].item())

tensor([[0.9768, 0.2859, 0.6554],
        [0.0844, 0.4349, 0.2885],
        [0.7860, 0.1730, 0.4071],
        [0.4848, 0.3739, 0.4475],
        [0.7929, 0.4569, 0.7941]])
x[:, 0] tensor([0.9768, 0.0844, 0.7860, 0.4848, 0.7929])
x[1, :] tensor([0.0844, 0.4349, 0.2885])
x[1, 1] tensor(0.4349)
x[1,1].item() 0.4349048137664795


In [27]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

p = x.view(-1,2) # see -1 can automatically detemine the necessary size
print(p.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
torch.Size([8, 2])


# NumPy

In [31]:
a = torch.ones(5)
print(a)
print(f"type(a): {type(a)}\n")
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(f"type(b): {type(b)}")

tensor([1., 1., 1., 1., 1.])
type(a): <class 'torch.Tensor'>

[1. 1. 1. 1. 1.]
type(b): <class 'numpy.ndarray'>


In [33]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

# -- you will see it will also modify the numpy(b) when you change a.

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [36]:
# numpy to torch with .from_numpy(x), or torch.tensor() to copy it
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)
print("\n")

# again be careful when modifying
a += 1
print(a)
print(b)  # This will change (from_numpy and to_numpy will share the same memory)
print(c)  # this will not get modified (torch.tensor(a) will createa copy in a different location)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# GPU Support

In [37]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device)  # create tensor on cpu and move to GPU
#x = x.to("cpu")
#x = x.to("cuda")  

x = torch.rand(2,2, device=device)  # or directy create them on GPU