In [1]:
import cv2
import numpy as np

# Shapes and Text

In [6]:
img = np.zeros((512,512,3),np.uint8)
print(img)
img[10:300,10:430]= 255,0,0 # define the region wher you want it to be blue

# for the below mention 
# 1- for which image
# 2- starting and ending points
# 3- color
# 4- thickness
cv2.line(img,(0,0),(img.shape[1],img.shape[0]),(0,255,0),3)  # (0,0),(img.shape[1],img.shape[0]) this is the starting point and the ending point
cv2.rectangle(img,(0,0),(250,350),(0,0,255),2) # cv2.FILLED to fill

# for circle centre and radius
cv2.circle(img,(400,50),30,(255,255,0),5)

# img, text, staring point, font, size or scale, colour, thickness
cv2.putText(img," OPENCV  ",(300,200),cv2.FONT_HERSHEY_COMPLEX,1,(0,150,0),3)


cv2.imshow("Image",img)

cv2.waitKey(0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


-1